language: node_js
node_js: stable

sudo: false

#cache
cache:
  directories:

notifications:
  email:
    recipients:
      - crotoc@gmail.com
    on_success: never
    on_failure: always

# S: Build Lifecycle
install:
    #  - npm install
    #  - npm install --save hexo-algolia
    #  - gem install travis
    #  - travis login --pro --github-token ${GH_TOKEN}
    #  - export HEXO_ALGOLIA_INDEXING_KEY=f20c1ed4145d79437191e2b985df0f41
    #  - hexo algolia

before_script:
    #  - export TZ='Asia/Shanghai'
    #  - chmod +x _travis.sh

script:
    # - hexo clean && hexo g

after_success:
 # - LAST_BUILD_NUMBER=68
 # - for i in $(seq 1 $LAST_BUILD_NUMBER ); do  travis logs $i --delete --force ; done

after_script:
    # - ./_travis.sh

# E: Build LifeCycle

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/crotoc/crotoc.github.io.git

